name: Test yt-dlp download

on:
  workflow_dispatch:

jobs:
  download-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Python
        run: |
          python3 --version

      - name: Install yt-dlp
        run: |
          pip install -U yt-dlp

      - name: Test extract
        run: |
          yt-dlp -F "https://youtu.be/-6a9RSBeADw?si=x2jOGjwY3exVVADnv"

      - name: Test download small
        run: |
          yt-dlp \
          -f "worstaudio/worst" \
          -o "test.%(ext)s" \
          "https://youtu.be/-6a9RSBeADw?si=x2jOGjwY3exVVADnv"

      - name: Show files
        run: |
          ls -lh
