name: yt-dlp-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y ffmpeg deno python3-pip


    - name: Install yt-dlp
      run: |
        python3 -m pip install --upgrade pip
        pip install -U yt-dlp


    - name: Check versions
      run: |
        yt-dlp --version
        deno --version


    - name: Test YouTube access
      run: |
        python3 - <<'PY'
        import requests

        for u in [
          "https://www.google.com",
          "https://www.youtube.com"
        ]:
            try:
                r=requests.get(u,timeout=20)
                print(u,r.status_code)
            except Exception as e:
                print("ERROR",u,e)
        PY


    - name: Download YouTube video
      run: |
        yt-dlp \
        --cookies cookies.txt \
        --js-runtimes deno \
        --remote-components ejs:github \
        --no-check-certificates \
        --force-ipv4 \
        --extractor-args "youtube:player_client=web" \
        -f "best[height<=720]/best" \
        -o "video.%(ext)s" \
        "https://youtu.be/-6a9RSBeADw?si=x2jOGjwY3exVVADnv"


    - name: Show downloaded file
      run: |
        ls -lh
        file video.*
