name: yt-dlp-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          python3 -m pip install -U yt-dlp
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Check network
        run: |
          python3 - <<'PY'
          import requests
          for url in [
              "https://www.google.com",
              "https://www.youtube.com"
          ]:
              try:
                  r=requests.get(url,timeout=20)
                  print(url, r.status_code)
              except Exception as e:
                  print(url,"FAILED",e)
          PY

      - name: Test YouTube formats with cookies
        run: |
          yt-dlp \
          --cookies cookies.txt \
          --no-check-certificates \
          --force-ipv4 \
          --extractor-args "youtube:player_client=android" \
          -F \
          "https://youtu.be/-6a9RSBeADw?si=x2jOGjwY3exVVADnv"

      - name: Download test
        run: |
          yt-dlp \
          --cookies cookies.txt \
          --no-check-certificates \
          --force-ipv4 \
          --extractor-args "youtube:player_client=android" \
          -f "best[height<=720]" \
          -o "video.%(ext)s" \
          "https://youtu.be/-6a9RSBeADw?si=x2jOGjwY3exVVADnv"

      - name: Show file
        run: |
          ls -lh
